#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME='run-container'
nl=$'\n'
tab='     '
SCRIPT_DES="Options: ${nl}${tab}--help/-h : Print This Help Message ${nl}\
${tab}--detached: Start Container In Background"
PROJECT_DIR="$SCRIPT_DIR/../.."
ENV_DIR="$PROJECT_DIR/env"
source $ENV_DIR/.env

function log(){
    echo -e "\e[92m$(date +"%r")\e[0m: \e[4;32m$SCRIPT_NAME\e[0m : >> $1"
}

function help(){
    echo -e "\n\e[4m$SCRIPT_NAME\e[0m\n\n\t$SCRIPT_DES" 
}

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        --detached)
            DETACHED="true"
            shift
            ;;
        --help)
            help "$SCRIPT_DES" "$SCRIPT_NAME"
            exit 0
            ;;
        *)
            log "Input not understood. See \e[3m--help\e[0m for information on using this command."
            exit 1
            ;;
    esac
done

if [ "${DETACHED}" == "true" ]
then
    log "Starting Up Container \e[3m$CONTAINER_NAME\e[0m In Detached Mode" $SCRIPT_NAME
    docker run --detached \ 
                --name $CONTAINER_NAME \
                --publish $NGINX_PORT:$NGINX_PORT \
                --env-file $ENV_DIR/.env \
                $IMAGE_NAME:$IMAGE_TAG
else

    log "Starting Up Container \e[3m$CONTAINER_NAME\e[0m In Foreground" $SCRIPT_NAME
    docker run --name $CONTAINER_NAME \
                --publish $NGINX_PORT:$NGINX_PORT \
                --env-file $ENV_DIR/.env \
                $IMAGE_NAME:$IMAGE_TAG
fi