// Action Types for Redux (pseudo-Enums)

export const LOAD_CURRENT_USER = "LOAD_CURRENT_USER";
export const LOAD_CURRENT_USER_SUCCESS = "LOAD_CURRENT_USER_SUCCESS";
export const LOAD_CURRENT_USER_FAILURE = "LOAD_CURRENT_USER_FAILURE";