#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCRIPT_NAME="lint-code"
SCRIPT_DES=$'Lints the source code for the frontend.'
PROJECT_DIR=$SCRIPT_DIR/..
if [ -f $PROJECT_dIR/.env ]
then
        source $PROJECT_DIR/.env
fi

npx eslint --quiet \
           --no-error-on-unmatched-pattern $PROJECT_DIR/frontend/src/** \
           --output-file $PROJECT_DIR/docs/linting/index.html \
           --format html \
           || true